# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'VideoDecoder-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoDecoder-Example
  pod 'VideoDecoder', :path => '../'

  target 'VideoDecoder-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VideoDecoder-ExampleUITests' do
    # Pods for testing
  end

end
